version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels: ["dependencies", "ci"]

  - package-ecosystem: terraform
    directory: /environments/dev
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: ["dependencies", "terraform"]

  - package-ecosystem: terraform
    directory: /environments/prod
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: ["dependencies", "terraform"]
