repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: ^\.github/workflows/.*\.yml$   # actionlint covers these
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: \.md$
    -   id: check-added-large-files
        args: ["--maxkb=512"]
    -   id: check-merge-conflict
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
    -   id: black
        files: ^scripts/.*\.py$
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
        args:
         - --hook-config=--retry-once-with-cleanup=true
    -   id: terraform_tflint
        args:
         - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    -   id: terraform_checkov
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    -   id: shellcheck
-   repo: https://github.com/crate-ci/typos
    rev: v1.45.0
    hooks:
    -   id: typos
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
    -   id: actionlint
